### ISSUE TITLE
Some issues: Moss Vale down trains; Kembla Grange; Sydenham

### ISSUE THREAD

**Issue by SHAIN2000** [jaboles/DVA5#26]
Hi, some issues I have noticed when using the GTFS feed:

- Down Southern Highlands trains that terminate at Moss Vale aren't appearing, only trains ending at Goulburn do. 
- South Coast Line trains announce trains that don't stop at Kembla Grange as being all stations, it doesn't announce Unanderra>Dapto and vice versa.
- No trains passing through Sydenham are announced, I assume because the substitutions file specifies to use "Watergardens" which is impacting the Sydney feed.

Thanks and the program is very impressive.

**Comment by jaboles** [comment]
Thanks for reporting! Should be fixed in the next version.

**Comment by jaboles** [comment]
Issue with Kiama trains should be fixed. Haven't been able to test the other issues yet (Campbelltown/Goulburn) but will try it soon.

**Comment by SHAIN2000** [comment]
> Issue with Kiama trains should be fixed. Haven't been able to test the other issues yet (Campbelltown/Goulburn) but will try it soon.

Thanks - update sorted out pretty much all of this. The Glenfield/Goulburn issue is still happening but that's not an issue with DVA...this trip divides at Moss Vale so it only shows the stops up to there which makes sense.
